# Copyright 2022-2025 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "fmo-pkgs"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/fmo-pkgs"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2025 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  ".github/dependabot.yml",
  ".github/workflows/codeql.yml",
  ".github/workflows/dependency-review.yml",
  ".pre-commit-config.yaml",
  "flake.lock",
  ".version",
  "README.md"
]
